### ISSUE TITLE
Hurricane Irma

### ISSUE THREAD

**Issue by chadicus** [RESTFest/2017-Greenville#2]
I know it is still very early, but the track of Irma seems to be going through Greenville.  How will attendees be notified of any schedule changes due to weather?

**Comment by orubel** [comment]
Travel light. Plus once it hits land it weakens and can divert. Plus it is
hitting Florida next week meaning we have a few days to 'escape'. I think
at most you may see some rain and wind but nothing drastic.

Owen Rubel
orubel@gmail.com

**Comment by orubel** [comment]
After watching the news just now too, they say it will hit on tuesday so we
will be arriving post-IRMA. So again, mostly rain and wind for us.



Owen Rubel
orubel@gmail.com

**Comment by chadicus** [comment]
Thanks @orubel, My main concern was just how would attendees be notified if the situation changes. It sounds like it's just a wait and see situation.

**Comment by orubel** [comment]
Well it sounds like the airport will cancel our flights if its bad.

I'm all for hosting in Seattle. We don't have hurricane season :)

Owen Rubel
orubel@gmail.com

**Comment by BigBlueHat** [comment]
Thanks for asking @chadicus!

We'll reach out via ti.to and any other channels we have/can should something change.

It currently looks like Monday and Tuesday of next week are the big rainy/windy days, and then things should lighten up after that.

I live in Greenville, SC, so I'll be watching the weather with acute interest. 😸 

We'll keep you all posted regardless!

Cheers!
🎩

**Comment by BigBlueHat** [comment]
@mamund just made a wiki page with some helpful weather stuff:
https://github.com/RESTFest/2017-Greenville/wiki/weather

Worth a look for anyone concerned. 😃
